# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_persondetails_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('content', models.CharField(max_length=20000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.PersonDetails')),
            ],
        ),
    ]
